version: '3.8'

services:
  # Frontend (React app)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mockup_frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - mockup_network

networks:
  mockup_network:
    driver: bridge
