version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mockup_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mockup_canvas}
      MYSQL_USER: ${MYSQL_USER:-mockupuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mockuppass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mockup_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mockup_backend
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-mockup_canvas}
      DB_USER: ${MYSQL_USER:-mockupuser}
      DB_PASSWORD: ${MYSQL_PASSWORD:-mockuppass}
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mockup_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend (React app)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mockup_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mockup_network

volumes:
  mysql_data:
    driver: local

networks:
  mockup_network:
    driver: bridge
