version: '3.8'

services:
  # Backend (Express API server)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mockup_backend
    restart: always
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      - ./uploads:/app/uploads
      - sqlite_data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3001}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT:-900000}
      - CLEANUP_CHECK_INTERVAL=${CLEANUP_CHECK_INTERVAL:-600000}
      - DB_PATH=/app/data/database.sqlite
    networks:
      - mockup_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (React app)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://mockupai.supover.com}
    container_name: mockup_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://mockupai.supover.com}
    networks:
      - mockup_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:5173"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  mockup_network:
    driver: bridge

volumes:
  session_data:
    driver: local
  sqlite_data:
    driver: local
